### ISSUE TITLE
Generator not working

### ISSUE THREAD

**Issue by moifort** [moifort/generator-jhipster-angular-ui#7]
Mac OSX
JHipster 2.26.1

Log attached:

``` bash
yo jhipster-angular-ui
     _-----_
    |       |    .--------------------------.
    |--(o)--|    |  Welcome to the JHipster |
   `---------´   |   AngularUI generator!   |
    ( _´U`_ )    '--------------------------'
    /___A___\    
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? Which module do you like to install on your JHipster application? Font Awesome, Awesome Bootstrap Checkbox (+Font Awesome), NGSwitchery, Angular Bootstrap Slider
Composing JHipster configuration with module AngularUI
Reading the JHipster project configuration for your module
events.js:141
      throw er; // Unhandled 'error' event
      ^

ReferenceError: name is not defined
    at Object.Generator.addBowerOverride (/usr/local/lib/node_modules/generator-jhipster/script-base.js:171:155)
    at module.exports.yeoman.generators.Base.extend.writing (/usr/local/lib/node_modules/generator-jhipster-angular-ui/generators/app/index.js:78:26)
    at /usr/local/lib/node_modules/generator-jhipster-angular-ui/node_modules/yeoman-generator/lib/base.js:430:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)

```

**Comment by moifort** [comment]
Fixed https://github.com/jhipster/generator-jhipster/commit/a4ff6a774eea7c8045a61848ff9fb9b0f978393f
